// SPDX-License-Identifier: CC0-1.0
// Public-domain example code (CC0) - see LICENSE. The CAS BACnet Stack itself is
// a separate, commercially licensed product and is not covered by CC0.
// =============================================================================
// BACnet Profile Example - B-SS (BACnet Smart Sensor) - Rust
//
// This example shows the *minimum* needed to implement the BACnet "B-SS"
// (Smart Sensor) device profile with the CAS BACnet Stack.
//
// A B-SS is "a simple sensing device with very limited resources" (ANSI/ASHRAE
// 135, Annex L.4.5). Its only mandatory capability is:
//
//     DS-RP-B  - respond to ReadProperty requests
//
// plus the ability to be discovered: it answers Who-Is with I-Am (handled
// automatically by the stack) and announces itself with an unsolicited I-Am on
// start-up.
//
// A B-SS does NOT require WriteProperty, COV, alarms/events, scheduling, or
// trending - so this example deliberately does NOT enable any of those. That is
// the whole point of a profile example: implement exactly what the profile
// asks for, nothing more.
//
// This is the Rust edition of BACnetProfileExample-B-SS-CPP / -CS / -Python -
// same objects, same names, same section layout, so you can diff the four side
// by side, and the FIRST Rust example in this series. The systematic
// difference here is the binding mechanism: Rust calls the native CAS BACnet
// Stack library through `libloading` (the vendored adapter in
// cas_bacnet_stack/, which does its own dlopen/GetProcAddress per call, like
// the C++ edition's explicit LoadBACnetFunctions() step - unlike C#, where the
// runtime resolves the library implicitly on first P/Invoke).
//
// THE ARCHITECTURAL CONSTRAINT THAT SHAPES THIS WHOLE FILE:
// BACnetStack_RegisterCallbackGetProperty*() takes `Option<extern "C" fn(...)>`
// - a plain, non-capturing function pointer, not a closure. So every
// Get*Property callback below is a free-standing `extern "C" fn` that reads
// device state from the `common::device_state::STATE` static (a
// `Lazy<Mutex<DeviceState>>`) rather than from a captured local - see
// device_state.rs's module doc for the full explanation. `main()` writes
// through that same lock (recording the discovered IP addressing at start-up;
// nudging the Analog Input from the interactive-command loop).
//
// PANIC SAFETY ACROSS THE FFI BOUNDARY. An unguarded Rust panic unwinding
// across an `extern "C" fn` callback into the C stack is undefined behavior.
// Every callback below wraps its body in `std::panic::catch_unwind` and
// returns `false` (leaving `errorCode` untouched - "no opinion", the same
// fallback a normal declining `return false` uses) on a caught panic, rather
// than letting it propagate. This stack has no CI-verified track record for
// Rust (its adapter carries its own "not compiled by any gate" warning - see
// cas_bacnet_stack/README.md), so defensive handling matters more here than in
// the other editions.
//
// The device exposes three read-only sensor objects plus the Network Port
// object that every BACnet device must have. Each object is given a colour name
// (a convention shared across this example series):
//
//     Device 389001          "Rainbow"    (instance configurable with --deviceID)
//     Analog Input  1        "Bronze"     (REAL, degrees Celsius; starts at 21.5)
//     Binary Input  1        "Emerald"    (active / inactive)
//     Multi-State Input 1    "Hot Pink"   (an enumerated state, 1..3)
//     Network Port 1         "Vermilion"  (the BACnet/IP port - required)
//
// To be a conformant BACnet device (Protocol_Revision 24) each object must
// expose its full set of REQUIRED properties. Most are generated by the stack
// (Object_Identifier, Object_Type, Status_Flags, Object_List, Protocol_*).
// Event_State is NOT generated - with no alarming configured it simply reads its
// datatype default of normal(0), correct by coincidence, not because the stack
// computes it. The handful that the application must supply are served by the
// Get*Property callbacks below, and a few are turned on with SetPropertyEnabled.
//
// Interactive commands (handled at the bottom of this file): a background
// thread reads LINE-buffered commands from stdin - h = help, q = quit,
// up/down = nudge Analog Input 1 by +/-1.1 - see "Interactive commands are a
// simplification" below for why this edition does not poll raw single
// keypresses like the C++/C#/Python editions. Command line: --port <n>,
// --deviceID <n>.
//
// All the UDP/stack plumbing lives in common/ so this file can stay focused on
// the BACnet logic.
// =============================================================================

mod cas_bacnet_stack;
mod common;

use std::os::raw::c_char;
use std::panic::catch_unwind;
use std::sync::atomic::{AtomicBool, Ordering};
use std::sync::mpsc;
use std::sync::Arc;
use std::time::Duration;

use cas_bacnet_stack::cas_bacnet_stack_adapters as bacnet;
use common::cas_example_helper;
use common::constants as c;
use common::device_state::STATE;

// -----------------------------------------------------------------------------
// 1. Example + device configuration
// -----------------------------------------------------------------------------
const APP_NAME: &str = "BACnet B-SS (Smart Sensor) Example - Rust";
const APP_VERSION: &str = "1.0.0";

// ---- Device identity: CHANGE ALL OF THIS BEFORE YOU SHIP --------------------
// Everything in this block is read by clients and shown to the operator in
// every discovery tool on the network. Left as-is, your product will appear on
// a real site announcing itself as a Chipkin demo. None of it is cosmetic:
// Object_Name must be unique across the BACnet internetwork, and Model_Name /
// Vendor_Identifier are what a building operator uses to identify your device.
// -------------------------------------------------------------------------

// Your BACnet Vendor Identifier. 389 = Chipkin Automation Systems; change this
// to YOUR company's vendor ID before shipping a product. Vendor IDs are
// assigned by ASHRAE - request one (free) at
// https://bacnet.org/assigned-vendor-ids/. Update VENDOR_NAME below to match.
const VENDOR_IDENTIFIER: u32 = 389;

// The Device object's Object_Name.
//
// THIS IS THE ONE THAT WILL BITE YOU. Object_Name must be unique across the
// whole BACnet internetwork, and here it is a COMPILE-TIME constant. The
// device instance is runtime-configurable via --deviceID, so it is easy to
// ship two units, configure their instances correctly, and still have BOTH
// announce Object_Name "Rainbow" - a spec violation, and a hard BTL failure.
// In a real product Object_Name must be per-unit configurable too: derive it
// from a serial number, DIP switches, a config file, or add a --deviceName
// argument.
const DEVICE_NAME: &str = "Rainbow";

// The Device object's Description. Change it to what YOUR device actually is;
// this string describes this tutorial.
const DEVICE_DESCRIPTION: &str = "Chipkin CAS BACnet Stack example - B-SS (Smart Sensor) profile. \
     Demonstrates DS-RP-B: ReadProperty plus Who-Is/I-Am with read-only sensor objects.";

// Device identity strings (read by clients, and used to populate I-Am).
const VENDOR_NAME: &str = "Chipkin Automation Systems";
const MODEL_NAME: &str = "CAS BACnet Stack Example - B-SS";
const FIRMWARE_REVISION: &str = "1.0.0";
const APPLICATION_SOFTWARE_VERSION: &str = "1.0.0";

// The sensor objects (all instance 1) and their colour names.
const ANALOG_INPUT_INSTANCE: u32 = 1; // "Bronze"
const BINARY_INPUT_INSTANCE: u32 = 1; // "Emerald"
const MULTI_STATE_INPUT_INSTANCE: u32 = 1; // "Hot Pink"
const MULTI_STATE_INPUT_NUMBER_OF_STATES: u32 = 3;
const MULTI_STATE_TEXT: [&str; 3] = ["On", "Off", "Auto"];
const BINARY_INPUT_1_VALUE: u32 = 0; // inactive - the series-wide starting value
const MULTI_STATE_INPUT_1_VALUE: u32 = 1; // state 1 ("On")

// The Network Port object - every BACnet device must have one. Its instance
// lives in common::constants::NETWORK_PORT_INSTANCE (the transport callbacks
// need it at compile time - see cas_example_helper.rs's module doc).
const MAX_APDU_LENGTH: u32 = 1476; // BACnet/IP APDU length

// -----------------------------------------------------------------------------
// 2. Property "get" callbacks
//
// The stack calls these when a client reads a property. For each data type the
// stack uses a separate callback. We return true (and fill *value) when we
// recognise the (object, property) pair, and false otherwise.
//
// THE errorCode OUT-PARAMETER. Every Get callback ends with a trailing
// errorCode pointer. The stack PRESETS it to success (84) before the call, and
// reads it only if we return false. That gives a declining callback two
// distinct meanings:
//
//   1. return false and LEAVE *errorCode ALONE -> "I have no opinion on this
//      property." The stack falls back to its own handling (see below).
//   2. return false and SET *errorCode          -> "This read fails, with THIS
//      BACnet error." The client gets exactly that Error-PDU.
//
// WHAT false-WITHOUT-AN-ERROR-CODE ACTUALLY DOES - the most important
// paragraph in this file, and the opposite of what most people assume. It
// does NOT reliably produce a BACnet error. The stack errors only for the
// handful of properties it refuses to invent: Present_Value,
// Number_Of_States, Relinquish_Default, Local_Date, Local_Time, and a Network
// Port's APDU_Length. For EVERYTHING ELSE, a false return means the stack
// SILENTLY SUBSTITUTES a default:
//     Object_Name -> the literal string "undefined"
//     Units       -> no-units (95)
//     otherwise   -> a datatype zero-value
//
// AND THAT FALLBACK IS LORE-BEARING, WHICH IS WHY WE DO NOT "FIX" IT HERE. The
// stack relies on the decline-and-fabricate path to answer required
// properties the application is not expected to serve - the Device's
// Max_APDU_Length_Accepted, APDU_Timeout and Number_Of_APDU_Retries among
// them. Set *errorCode ONLY where THIS device knows the read is wrong. There
// is exactly one such case below (State_Text with an out-of-range array
// index); the catch-all `return false` at the end of each callback
// deliberately leaves *errorCode alone.
//
// ADDING AN OBJECT? See TUTORIAL.md "Add a second analog input" before you
// do - a half-added object does NOT fail loudly (see above).
// -----------------------------------------------------------------------------

/// REAL (floating point) - the Analog Input's Present_Value.
extern "C" fn get_property_real(
    device_instance: u32,
    object_type: u16,
    object_instance: u32,
    property_identifier: u32,
    value: *mut f32,
    _use_array_index: bool,
    _property_array_index: u32,
    _error_code: *mut u32,
) -> bool {
    catch_unwind(|| {
        let state = STATE.lock().unwrap_or_else(|e| e.into_inner());
        if device_instance == state.device_instance
            && object_type == c::OBJECT_TYPE_ANALOG_INPUT
            && object_instance == ANALOG_INPUT_INSTANCE
            && property_identifier == c::PROPERTY_IDENTIFIER_PRESENT_VALUE
        {
            // ON REAL HARDWARE: return the live sensor reading here. Read it
            // from a cached variable that your hardware updates (as
            // state.analog_input_1_value is), NOT directly from a
            // slow/blocking device (I2C, SPI, ADC conversion): this callback
            // runs on the BACnetStack_Tick() call, so blocking it delays all
            // BACnet processing. Sample the sensor on a timer/another thread
            // and just hand back the latest value from here.
            // SAFETY: `value` is a valid, aligned, writable f32 out-param for
            // the duration of this call, per the stack's documented contract.
            unsafe { *value = state.analog_input_1_value };
            true
        } else {
            false
        }
    })
    .unwrap_or(false)
}

/// ENUMERATED - the Binary Input's Present_Value (0 = inactive, 1 = active),
/// the Analog Input's Units, and the Network Port's BACnet_IP_Mode.
extern "C" fn get_property_enumerated(
    device_instance: u32,
    object_type: u16,
    object_instance: u32,
    property_identifier: u32,
    value: *mut u32,
    _use_array_index: bool,
    _property_array_index: u32,
    _error_code: *mut u32,
) -> bool {
    catch_unwind(|| {
        let state = STATE.lock().unwrap_or_else(|e| e.into_inner());
        if device_instance != state.device_instance {
            return false;
        }
        if object_type == c::OBJECT_TYPE_BINARY_INPUT && object_instance == BINARY_INPUT_INSTANCE {
            if property_identifier == c::PROPERTY_IDENTIFIER_PRESENT_VALUE {
                // ON REAL HARDWARE: return your cached input state here - the
                // same rule as get_property_real above applies.
                unsafe { *value = BINARY_INPUT_1_VALUE };
                return true;
            }
            if property_identifier == c::PROPERTY_IDENTIFIER_POLARITY {
                unsafe { *value = c::POLARITY_NORMAL }; // required property of a Binary Input
                return true;
            }
        }
        if object_type == c::OBJECT_TYPE_ANALOG_INPUT
            && object_instance == ANALOG_INPUT_INSTANCE
            && property_identifier == c::PROPERTY_IDENTIFIER_UNITS
        {
            unsafe { *value = c::ENGINEERING_UNITS_DEGREES_CELSIUS };
            return true;
        }
        if object_type == c::OBJECT_TYPE_NETWORK_PORT
            && object_instance == c::NETWORK_PORT_INSTANCE
            && property_identifier == c::PROPERTY_IDENTIFIER_BACNET_IP_MODE
        {
            unsafe { *value = c::BACNET_IP_MODE_NORMAL }; // not foreign-device, not BBMD
            return true;
        }
        false
    })
    .unwrap_or(false)
}

/// UNSIGNED INTEGER - the Multi-State Input's Present_Value, and the Device's
/// Vendor_Identifier (the stack also uses Vendor_Identifier to build I-Am).
extern "C" fn get_property_unsigned_integer(
    device_instance: u32,
    object_type: u16,
    object_instance: u32,
    property_identifier: u32,
    value: *mut u32,
    use_array_index: bool,
    property_array_index: u32,
    _error_code: *mut u32,
) -> bool {
    catch_unwind(|| {
        let state = STATE.lock().unwrap_or_else(|e| e.into_inner());
        if device_instance != state.device_instance {
            return false;
        }
        if object_type == c::OBJECT_TYPE_MULTI_STATE_INPUT && object_instance == MULTI_STATE_INPUT_INSTANCE {
            if property_identifier == c::PROPERTY_IDENTIFIER_PRESENT_VALUE {
                unsafe { *value = MULTI_STATE_INPUT_1_VALUE }; // valid range is 1..Number_Of_States
                return true;
            }
            if property_identifier == c::PROPERTY_IDENTIFIER_NUMBER_OF_STATES {
                unsafe { *value = MULTI_STATE_INPUT_NUMBER_OF_STATES }; // required property
                return true;
            }
            // State_Text is an array. The stack asks for its LENGTH here
            // (array index 0) before reading each element via
            // get_property_character_string.
            if property_identifier == c::PROPERTY_IDENTIFIER_STATE_TEXT
                && use_array_index
                && property_array_index == 0
            {
                unsafe { *value = MULTI_STATE_INPUT_NUMBER_OF_STATES };
                return true;
            }
        }
        if object_type == c::OBJECT_TYPE_DEVICE
            && object_instance == state.device_instance
            && property_identifier == c::PROPERTY_IDENTIFIER_VENDOR_IDENTIFIER
        {
            unsafe { *value = VENDOR_IDENTIFIER };
            return true;
        }
        if object_type == c::OBJECT_TYPE_NETWORK_PORT && object_instance == c::NETWORK_PORT_INSTANCE {
            if property_identifier == c::PROPERTY_IDENTIFIER_APDU_LENGTH {
                unsafe { *value = MAX_APDU_LENGTH };
                return true;
            }
            if property_identifier == c::PROPERTY_IDENTIFIER_REFERENCE_PORT {
                unsafe { *value = c::NETWORK_PORT_REFERENCE_PORT_NONE };
                return true;
            }
            if property_identifier == c::PROPERTY_IDENTIFIER_BACNET_IP_UDP_PORT {
                unsafe { *value = state.bacnet_ip_udp_port as u32 };
                return true;
            }
        }
        false
    })
    .unwrap_or(false)
}

/// BOOLEAN - Out_Of_Service is a required property of every input object and
/// of the Network Port. This is a read-only sensor, so nothing is ever out of
/// service: always false.
extern "C" fn get_property_bool(
    device_instance: u32,
    object_type: u16,
    _object_instance: u32,
    property_identifier: u32,
    value: *mut bool,
    _use_array_index: bool,
    _property_array_index: u32,
    _error_code: *mut u32,
) -> bool {
    catch_unwind(|| {
        let state = STATE.lock().unwrap_or_else(|e| e.into_inner());
        if device_instance != state.device_instance {
            return false;
        }
        if property_identifier == c::PROPERTY_IDENTIFIER_OUT_OF_SERVICE
            && (object_type == c::OBJECT_TYPE_ANALOG_INPUT
                || object_type == c::OBJECT_TYPE_BINARY_INPUT
                || object_type == c::OBJECT_TYPE_MULTI_STATE_INPUT
                || object_type == c::OBJECT_TYPE_NETWORK_PORT)
        {
            unsafe { *value = false };
            return true;
        }
        false
    })
    .unwrap_or(false)
}

/// OCTET STRING - the Network Port's BACnet/IP addressing. The stack cannot
/// know the host's IP, so the application must supply IP_Address and
/// IP_Subnet_Mask (and IP_Default_Gateway). Each is four octets. The stack
/// also reads IP_Address (with BACnet_IP_UDP_Port) to build the port's
/// six-octet MAC_Address.
extern "C" fn get_property_octet_string(
    device_instance: u32,
    object_type: u16,
    object_instance: u32,
    property_identifier: u32,
    value: *mut u8,
    value_element_count: *mut u32,
    max_element_count: u32,
    _use_array_index: bool,
    _property_array_index: u32,
    _error_code: *mut u32,
) -> bool {
    catch_unwind(|| {
        let state = STATE.lock().unwrap_or_else(|e| e.into_inner());
        if device_instance != state.device_instance
            || object_type != c::OBJECT_TYPE_NETWORK_PORT
            || object_instance != c::NETWORK_PORT_INSTANCE
            || max_element_count < 4
        {
            return false;
        }
        let source = if property_identifier == c::PROPERTY_IDENTIFIER_IP_ADDRESS {
            state.ip_address
        } else if property_identifier == c::PROPERTY_IDENTIFIER_IP_SUBNET_MASK {
            state.ip_subnet_mask
        } else if property_identifier == c::PROPERTY_IDENTIFIER_IP_DEFAULT_GATEWAY {
            state.ip_default_gateway
        } else {
            return false;
        };
        unsafe {
            for i in 0..4 {
                *value.add(i) = source[i];
            }
            *value_element_count = 4;
        }
        true
    })
    .unwrap_or(false)
}

/// Copy a `&str` into the stack's character-string buffer as UTF-8 and set
/// the element count + encoding. SAFETY: caller guarantees `value` has room
/// for at least `max_element_count` bytes.
unsafe fn write_character_string(
    text: &str,
    value: *mut c_char,
    value_element_count: *mut u32,
    max_element_count: u32,
    encoding_type: *mut u8,
) -> bool {
    let mut bytes = text.as_bytes();
    if bytes.len() as u32 > max_element_count {
        // Truncate SILENTLY to fit the stack's buffer. max_element_count is
        // MAX_CHARACTER_STRING_SIZE (256 in this build), and our longest
        // string (DEVICE_DESCRIPTION) fits with room to spare - so this never
        // trips here. But if you build with a smaller embedded buffer, that
        // limit drops, and a long Object_Name or Description would be clipped
        // mid-word with nothing on the wire or console to tell you. If you
        // lengthen any served string, check it against
        // MAX_CHARACTER_STRING_SIZE for your target, or make this truncation
        // loud.
        bytes = &bytes[..max_element_count as usize];
    }
    for (i, b) in bytes.iter().enumerate() {
        *value.add(i) = *b as c_char;
    }
    *value_element_count = bytes.len() as u32;
    *encoding_type = c::CHARACTER_STRING_ENCODING_UTF8;
    true
}

/// CHARACTER STRING - Object_Name for each object, and the device Description.
extern "C" fn get_property_character_string(
    device_instance: u32,
    object_type: u16,
    object_instance: u32,
    property_identifier: u32,
    value: *mut c_char,
    value_element_count: *mut u32,
    max_element_count: u32,
    encoding_type: *mut u8,
    use_array_index: bool,
    property_array_index: u32,
    error_code: *mut u32,
) -> bool {
    catch_unwind(|| {
        let state = STATE.lock().unwrap_or_else(|e| e.into_inner());
        if device_instance != state.device_instance {
            return false;
        }

        // State_Text (optional) - one label per state of the Multi-State
        // Input. It is a BACnet array, so the stack asks for one element at
        // a time by index (1..Number_Of_States). Present_Value 1 -> "On",
        // 2 -> "Off", 3 -> "Auto".
        if object_type == c::OBJECT_TYPE_MULTI_STATE_INPUT
            && object_instance == MULTI_STATE_INPUT_INSTANCE
            && property_identifier == c::PROPERTY_IDENTIFIER_STATE_TEXT
            && use_array_index
        {
            if (1..=MULTI_STATE_INPUT_NUMBER_OF_STATES).contains(&property_array_index) {
                return unsafe {
                    write_character_string(
                        MULTI_STATE_TEXT[(property_array_index - 1) as usize],
                        value,
                        value_element_count,
                        max_element_count,
                        encoding_type,
                    )
                };
            }
            // The one place in this file where naming an error is clearly
            // right: the client asked for State_Text[n] and this object has
            // no element n. That is not "no opinion" - it is a wrong read,
            // and the spec has a code for it. Without this the client would
            // silently receive an empty string.
            unsafe { *error_code = c::ERROR_CODE_INVALID_ARRAY_INDEX };
            return false;
        }

        // Object_Name - the colour name for each object.
        if property_identifier == c::PROPERTY_IDENTIFIER_OBJECT_NAME {
            let name = if object_type == c::OBJECT_TYPE_DEVICE && object_instance == state.device_instance {
                Some(DEVICE_NAME)
            } else if object_type == c::OBJECT_TYPE_ANALOG_INPUT && object_instance == ANALOG_INPUT_INSTANCE {
                Some("Bronze")
            } else if object_type == c::OBJECT_TYPE_BINARY_INPUT && object_instance == BINARY_INPUT_INSTANCE {
                Some("Emerald")
            } else if object_type == c::OBJECT_TYPE_MULTI_STATE_INPUT
                && object_instance == MULTI_STATE_INPUT_INSTANCE
            {
                Some("Hot Pink")
            } else if object_type == c::OBJECT_TYPE_NETWORK_PORT && object_instance == c::NETWORK_PORT_INSTANCE {
                Some("Vermilion")
            } else {
                None
            };
            if let Some(name) = name {
                return unsafe {
                    write_character_string(name, value, value_element_count, max_element_count, encoding_type)
                };
            }
        }

        // The remaining strings are all on the Device object - its identity,
        // read by clients and used to populate the device's I-Am / object
        // list.
        if object_type == c::OBJECT_TYPE_DEVICE && object_instance == state.device_instance {
            let text = if property_identifier == c::PROPERTY_IDENTIFIER_DESCRIPTION {
                Some(DEVICE_DESCRIPTION)
            } else if property_identifier == c::PROPERTY_IDENTIFIER_VENDOR_NAME {
                Some(VENDOR_NAME)
            } else if property_identifier == c::PROPERTY_IDENTIFIER_MODEL_NAME {
                Some(MODEL_NAME)
            } else if property_identifier == c::PROPERTY_IDENTIFIER_FIRMWARE_REVISION {
                Some(FIRMWARE_REVISION)
            } else if property_identifier == c::PROPERTY_IDENTIFIER_APPLICATION_SOFTWARE_VERSION {
                Some(APPLICATION_SOFTWARE_VERSION)
            } else {
                None
            };
            if let Some(text) = text {
                return unsafe {
                    write_character_string(text, value, value_element_count, max_element_count, encoding_type)
                };
            }
        }

        false
    })
    .unwrap_or(false)
}

// -----------------------------------------------------------------------------
// 3. Interactive commands are a simplification - see TUTORIAL.md
// -----------------------------------------------------------------------------
// The C++ edition polls raw console keys (including arrow-key escape
// sequences) every millisecond in its own loop. The C# edition uses .NET's
// built-in non-blocking Console.KeyAvailable/ReadKey. The Python edition picks
// a platform-appropriate raw-mode poller (msvcrt on Windows, termios/tty/select
// on POSIX). Rust's standard library has NO non-blocking single-keypress read
// on any platform - that needs a platform-specific crate (e.g. `crossterm`),
// which this example deliberately avoids to keep the dependency list to
// exactly `libloading`/`once_cell`/`ctrlc` (see Cargo.toml).
//
// So this edition reads LINE-buffered commands instead: type a command and
// press Enter. A background thread blocks on stdin's `read_line()` (there is
// no portable way to make that non-blocking in std either) and forwards
// completed commands to the main loop over an `mpsc` channel, which the main
// loop drains without blocking (`try_recv()`) once per tick. This also means
// there is no TTY check to skip: a background/piped run (the CI smoke test,
// for instance) simply sees stdin hit EOF immediately, the reader thread
// exits quietly, and the device keeps running - Ctrl+C still works via the
// handler below.
// -----------------------------------------------------------------------------

enum Command {
    Help,
    Quit,
    Up,
    Down,
}

fn spawn_command_reader() -> mpsc::Receiver<Command> {
    let (tx, rx) = mpsc::channel();
    std::thread::spawn(move || {
        let stdin = std::io::stdin();
        loop {
            let mut line = String::new();
            match stdin.read_line(&mut line) {
                Ok(0) => break, // EOF - not an interactive console (or it closed)
                Ok(_) => {
                    let command = match line.trim().to_ascii_lowercase().as_str() {
                        "h" | "help" => Some(Command::Help),
                        "q" | "quit" => Some(Command::Quit),
                        "up" | "u" => Some(Command::Up),
                        "down" | "d" => Some(Command::Down),
                        _ => None,
                    };
                    if let Some(command) = command {
                        if tx.send(command).is_err() {
                            break; // main loop has exited
                        }
                    }
                }
                Err(_) => break,
            }
        }
    });
    rx
}

fn print_help() {
    cas_example_helper::print_version(APP_NAME, APP_VERSION);
    println!("Commands (type + Enter): h = this help, q = quit, up/down = Analog Input 1 +/- 1.1");
}

// -----------------------------------------------------------------------------
// 4. main()
// -----------------------------------------------------------------------------

fn parse_args() -> Result<(u16, u32), i32> {
    let mut port: u16 = 47808;
    let mut device_id: u32 = 389001;
    let args: Vec<String> = std::env::args().skip(1).collect();
    let mut i = 0;
    while i < args.len() {
        match args[i].as_str() {
            "--help" | "-h" => {
                println!("{APP_NAME}");
                println!("Options:");
                println!("  --help              Show this help and exit");
                println!("  --version           Show version information and exit");
                println!("  --deviceID <inst>   BACnet Device instance (0..4194302, default 389001)");
                println!("  --port <n>          BACnet/IP UDP port to listen on (default 47808)");
                return Err(0);
            }
            "--version" => {
                // Printed by the caller once the library is confirmed loadable.
                return Err(-1); // sentinel: "print version and exit 0"
            }
            "--port" => {
                i += 1;
                let raw = args.get(i).map(String::as_str).unwrap_or("");
                match cas_example_helper::parse_port(raw) {
                    Ok(v) => port = v,
                    Err(e) => {
                        eprintln!("Error: {e}");
                        return Err(1);
                    }
                }
            }
            "--deviceID" => {
                i += 1;
                let raw = args.get(i).map(String::as_str).unwrap_or("");
                match cas_example_helper::parse_device_id(raw) {
                    Ok(v) => device_id = v,
                    Err(e) => {
                        eprintln!("Error: {e}");
                        return Err(1);
                    }
                }
            }
            other => {
                eprintln!("Error: unrecognized argument \"{other}\" (see --help)");
                return Err(1);
            }
        }
        i += 1;
    }
    Ok((port, device_id))
}

fn main() -> std::process::ExitCode {
    let (port, device_id, want_version_only) = match parse_args() {
        Ok((p, d)) => (p, d, false),
        Err(-1) => (47808, 389001, true),
        Err(0) => return std::process::ExitCode::SUCCESS,
        Err(_) => return std::process::ExitCode::FAILURE,
    };

    {
        let mut state = STATE.lock().unwrap_or_else(|e| e.into_inner());
        state.device_instance = device_id;
    }

    // --- Load the CAS BACnet Stack + print version ----------------------------
    // Unlike the C# edition (where the runtime resolves the native library
    // implicitly on first P/Invoke), this is an explicit load step like the
    // C++/Python editions: the first call into `bacnet::` forces the
    // `once_cell::sync::Lazy<libloading::Library>` in
    // cas_bacnet_stack_adapters.rs, which panics with a descriptive message if
    // the library cannot be found (see that file's `load_library()` for the
    // search order this vendored copy uses). Catch that panic here so a
    // missing/mismatched native library is reported the same way the other
    // editions report it, instead of a raw Rust panic backtrace.
    let version_result = catch_unwind(|| {
        cas_example_helper::print_version(APP_NAME, APP_VERSION);
    });
    if version_result.is_err() {
        eprintln!("Error: failed to load the CAS BACnet Stack native library.");
        eprintln!(
            "Copy CASBACnetStack_x64_Release.dll (Windows) / libCASBACnetStack_x64_Release.so (Linux) \
             next to this executable - see README.md \"Build the native CAS BACnet Stack library\"."
        );
        return std::process::ExitCode::FAILURE;
    }
    if want_version_only {
        return std::process::ExitCode::SUCCESS;
    }

    // --- Bind the BACnet/IP socket -------------------------------------------
    if let Err(e) = cas_example_helper::setup_udp(port) {
        eprintln!("Error: could not bind UDP port {port}: {e}");
        eprintln!("Is another BACnet device already running on this machine? Try --port.");
        return std::process::ExitCode::FAILURE;
    }

    // Capture the BACnet/IP addressing the Network Port object will report.
    let local = cas_example_helper::get_local_ipv4();
    {
        let mut state = STATE.lock().unwrap_or_else(|e| e.into_inner());
        state.bacnet_ip_udp_port = port;
        state.ip_address = local.address.octets();
        state.ip_subnet_mask = local.netmask.octets();
    }
    println!("FYI: listening on {}:{port} (broadcast {})", local.address, local.broadcast);

    // --- Register callbacks ---------------------------------------------------
    // The transport + time callbacks are shared boilerplate, keyed to
    // common::constants::NETWORK_PORT_INSTANCE.
    cas_example_helper::register_common_callbacks();

    // The property callbacks are specific to this example.
    let ok = bacnet::BACnetStack_RegisterCallbackGetPropertyReal(Some(get_property_real)).is_ok()
        && bacnet::BACnetStack_RegisterCallbackGetPropertyEnumerated(Some(get_property_enumerated)).is_ok()
        && bacnet::BACnetStack_RegisterCallbackGetPropertyUnsignedInteger(Some(get_property_unsigned_integer))
            .is_ok()
        && bacnet::BACnetStack_RegisterCallbackGetPropertyCharacterString(Some(get_property_character_string))
            .is_ok()
        && bacnet::BACnetStack_RegisterCallbackGetPropertyBool(Some(get_property_bool)).is_ok()
        && bacnet::BACnetStack_RegisterCallbackGetPropertyOctetString(Some(get_property_octet_string)).is_ok();
    if !ok {
        eprintln!("Error: failed to register one or more Get*Property callbacks.");
        return std::process::ExitCode::FAILURE;
    }

    // --- Create the device -----------------------------------------------------
    if !bacnet::BACnetStack_AddDevice(device_id).unwrap_or(false) {
        eprintln!("Error: Failed to add the Device {device_id}.");
        return std::process::ExitCode::FAILURE;
    }

    // Enable ReadProperty (DS-RP-B) - the one mandatory service for B-SS. We
    // set it explicitly to make the profile requirement obvious.
    //
    // We deliberately do NOT enable WriteProperty, ReadPropertyMultiple,
    // SubscribeCOV, or any alarm/event service: a Smart Sensor does not
    // require them, so a faithful B-SS example leaves them off.
    if !bacnet::BACnetStack_SetServiceEnabled(device_id, c::SERVICE_READ_PROPERTY, true).unwrap_or(false) {
        eprintln!("Error: Failed to enable the ReadProperty service.");
        return std::process::ExitCode::FAILURE;
    }

    // Discovery: Who-Is/I-Am (DM-DDB-B) and Who-Has/I-Have (DM-DOB-B).
    //
    // These need enabling even though the device already ANSWERS them. The
    // stack's service defaults are whoIs + whoHas + readProperty only - iAm
    // and iHave are left false. Who-Is is answered and the start-up I-Am is
    // sent regardless, because neither is gated on the bit; but
    // Protocol_Services_Supported is emitted verbatim from that bitstring, so
    // without these calls the device DOES I-Am and I-Have while telling every
    // client it supports neither.
    let discovery_ok = bacnet::BACnetStack_SetServiceEnabled(device_id, c::SERVICE_WHO_IS, true).unwrap_or(false)
        && bacnet::BACnetStack_SetServiceEnabled(device_id, c::SERVICE_I_AM, true).unwrap_or(false)
        && bacnet::BACnetStack_SetServiceEnabled(device_id, c::SERVICE_WHO_HAS, true).unwrap_or(false)
        && bacnet::BACnetStack_SetServiceEnabled(device_id, c::SERVICE_I_HAVE, true).unwrap_or(false);
    if !discovery_ok {
        eprintln!("Error: Failed to enable the discovery services (Who-Is/I-Am, Who-Has/I-Have).");
        return std::process::ExitCode::FAILURE;
    }

    // --- Add the read-only sensor objects ---------------------------------------
    if !bacnet::BACnetStack_AddObject(device_id, c::OBJECT_TYPE_ANALOG_INPUT, ANALOG_INPUT_INSTANCE)
        .unwrap_or(false)
    {
        eprintln!("Error: Failed to add Analog Input {ANALOG_INPUT_INSTANCE} (Bronze).");
        return std::process::ExitCode::FAILURE;
    }
    if !bacnet::BACnetStack_AddObject(device_id, c::OBJECT_TYPE_BINARY_INPUT, BINARY_INPUT_INSTANCE)
        .unwrap_or(false)
    {
        eprintln!("Error: Failed to add Binary Input {BINARY_INPUT_INSTANCE} (Emerald).");
        return std::process::ExitCode::FAILURE;
    }
    if !bacnet::BACnetStack_AddObject(device_id, c::OBJECT_TYPE_MULTI_STATE_INPUT, MULTI_STATE_INPUT_INSTANCE)
        .unwrap_or(false)
    {
        eprintln!("Error: Failed to add Multi-State Input {MULTI_STATE_INPUT_INSTANCE} (Hot Pink).");
        return std::process::ExitCode::FAILURE;
    }

    // --- Add the Network Port object --------------------------------------------
    // Every BACnet device (Protocol_Revision 17+) must have at least one
    // Network Port object describing the port it talks on. This one is the
    // BACnet/IP application port; it is the lowest layer, so its reference
    // port is "none". networkNumber 0 with quality "unknown" describes a
    // local port that has not learned its network number - the right answer
    // for a device that is not a router and has not been told one.
    if !bacnet::BACnetStack_AddNetworkPortObject(
        device_id,
        c::NETWORK_PORT_INSTANCE,
        c::NETWORK_PORT_NETWORK_TYPE_IPV4,
        c::NETWORK_PORT_PROTOCOL_LEVEL_BACNET_APPLICATION,
        0, // networkNumber: not configured
        c::NETWORK_NUMBER_QUALITY_UNKNOWN,
        c::NETWORK_PORT_REFERENCE_PORT_NONE,
    )
    .unwrap_or(false)
    {
        eprintln!("Error: Failed to add Network Port 1 (Vermilion).");
        return std::process::ExitCode::FAILURE;
    }

    // --- Enable the OPTIONAL properties we choose to expose ---------------------
    // The stack automatically enables an object's REQUIRED properties when the
    // object is added - so Units, Polarity, Number_Of_States, Out_Of_Service,
    // and the Network Port's BACnet/IP addressing are already enabled; our
    // Get* callbacks just supply their values. Only OPTIONAL properties need
    // SetPropertyEnabled. State_Text is optional on a Multi-State Input, so we
    // enable it here (and serve it in get_property_character_string).
    //
    // The Device's Description is optional too, and it is an easy one to get
    // wrong: serving it from a Get callback is NOT enough. The stack checks
    // IsPropertyEnabled BEFORE it ever reaches the callbacks, and for an
    // optional property that check falls back to "is it required?" - which is
    // false. So a Description branch in the callback without this enable is
    // DEAD CODE, and the client reads back Error: unknown-property.
    if !bacnet::BACnetStack_SetPropertyEnabled(
        device_id,
        c::OBJECT_TYPE_DEVICE,
        device_id,
        c::PROPERTY_IDENTIFIER_DESCRIPTION,
        true,
    )
    .unwrap_or(false)
    {
        eprintln!("Error: Failed to enable Description on the Device object.");
        return std::process::ExitCode::FAILURE;
    }
    if !bacnet::BACnetStack_SetPropertyEnabled(
        device_id,
        c::OBJECT_TYPE_MULTI_STATE_INPUT,
        MULTI_STATE_INPUT_INSTANCE,
        c::PROPERTY_IDENTIFIER_STATE_TEXT,
        true,
    )
    .unwrap_or(false)
    {
        eprintln!("Error: Failed to enable State_Text on Multi-State Input 1 (Hot Pink).");
        return std::process::ExitCode::FAILURE;
    }

    // Who-Is is answered automatically. The spec also requires a device to
    // announce itself on start-up, so broadcast an unsolicited I-Am now (to
    // the local subnet broadcast - the Network Port's own network).
    if !cas_example_helper::send_i_am(device_id, port) {
        eprintln!("Error: SendIAm failed.");
        return std::process::ExitCode::FAILURE;
    }

    println!("FYI: Device {device_id} (\"{DEVICE_NAME}\") ready. Vendor ID {VENDOR_IDENTIFIER}. Type 'h' + Enter for help.");

    // --- Graceful Ctrl+C shutdown ------------------------------------------------
    let running = Arc::new(AtomicBool::new(true));
    {
        let running = Arc::clone(&running);
        // ctrlc is the simplest reliable cross-platform SIGINT/Ctrl+C hook
        // available without hand-rolling per-OS signal handling (POSIX
        // sigaction vs. Windows SetConsoleCtrlHandler) - see Cargo.toml.
        ctrlc::set_handler(move || {
            running.store(false, Ordering::SeqCst); // handle it ourselves instead of the process dying mid-tick
        })
        .expect("failed to install the Ctrl+C handler");
    }

    let commands = spawn_command_reader();

    // --- Run the stack -------------------------------------------------------------
    // BACnetStack_Tick() processes incoming messages and timers. Call it
    // continuously, and drain any completed interactive command. The stack is
    // single-threaded by contract - everything that touches it happens on this
    // one loop; the reader thread only ever sends completed Command values
    // over the channel, never calls into the stack itself.
    while running.load(Ordering::SeqCst) {
        let _ = bacnet::BACnetStack_Tick();

        match commands.try_recv() {
            Ok(Command::Help) => print_help(),
            Ok(Command::Quit) => running.store(false, Ordering::SeqCst),
            Ok(Command::Up) => {
                let mut state = STATE.lock().unwrap_or_else(|e| e.into_inner());
                state.analog_input_1_value += 1.1;
                println!("Analog Input 1 (Bronze) = {:.1} C", state.analog_input_1_value);
            }
            Ok(Command::Down) => {
                let mut state = STATE.lock().unwrap_or_else(|e| e.into_inner());
                state.analog_input_1_value -= 1.1;
                println!("Analog Input 1 (Bronze) = {:.1} C", state.analog_input_1_value);
            }
            Err(_) => {} // nothing waiting this tick
        }

        std::thread::sleep(Duration::from_millis(1)); // be a good citizen, don't spin the CPU
    }

    cas_example_helper::shutdown_udp();
    println!("FYI: stopped.");
    std::process::ExitCode::SUCCESS
}
